# Site settings
title: Mark Birbeck's Blog
email: mark.birbeck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  From agile and lean to big data and the semantic web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://markbirbeck.com" # the base hostname & protocol for your site
twitter_username: markbirbeck
github_username:  markbirbeck

# Build settings
markdown: redcarpet
rdiscount:
  extensions: [smart]
highlighter: true

exclude: [
  'config.ru',
  'Gemfile',
  'Gemfile.lock',
  node_modules,
  package.json,
  'post-deploy-tests.sh',
  'vendor',
  'wercker.yml'
]