# Site settings
title: Mark Birbeck's Blog
email: mark.birbeck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  From agile and lean to big data and the semantic web.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
url: "http://markbirbeck.com" # the base hostname & protocol for your site
twitter_username: markbirbeck
github_username:  markbirbeck
disqus_shortname: markbirbeck
disqus_identifier: http://markbirbeck.com
google_tag_manager: GTM-5Z8G6B

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - node_modules
  - package.json
  - 'post-deploy-tests.sh'
  - 'vendor'
  - 'wercker.yml'
  - '_site.from.jekyll'
  - 'config.ru'

layouts: ./node_modules/layout-liquid-jekyll-basic/layouts
includes: ./node_modules/layout-liquid-jekyll-basic/partials
#verbose: true